{
  "openapi": "3.0.0",
  "info": {
    "title": "KIKIB API SERVER by node sequelizer",
    "description": "node sequelizer로 만든 api server입니다.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://kikibus.iptime.org:8484"
    }
  ],
  "paths": {
    "/api/notice/": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "notice list.",
        "description": null,
        "tags": ["notice"],
        "responses": {
          "200": {
            "description": "A JSON array of notice info",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "contents": {
                      "type": "string",
                      "example": "This is body"
                    },
                    "created_date": {
                      "type": "datetime",
                      "example": "2022-01-01T00:00:00.000Z"
                    },
                    "file": {
                      "type": "file"
                    },
                    "title": {
                      "type": "string",
                      "example": "Simple notice!!"
                    },
                    "category": {
                      "type": "string",
                      "example": "COMPANY"
                    },
                    "company_id": {
                      "type": "int",
                      "example": 1
                    },
                    "place_id": {
                      "type": "int",
                      "example": 1
                    },
                    "route_id": {
                      "type": "int",
                      "example": 20
                    },
                    "hit": {
                      "type": "int",
                      "example": 1
                    },
                    "writer_id": {
                      "type": "int",
                      "example": 1
                    },
                    "piclinkarray": {
                      "type": "string",
                      "example": ["222/img1.jpg", "222/img2.jpg"]
                    },
                    "youtubearray": {
                      "type": "string",
                      "example": ["https://www.youtube.com/watch?v=c64aupy8WhY"]
                    },
                    "urgent": {
                      "type": "boolean",
                      "example": false
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/api/alert/": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "alert list.",
        "description": "개인별 관련알림리스트(배차,휴무교환,연차,근무변경, dayoff)",
        "tags": ["alert"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/api/managerReplaceList": {
      "post": {
        "description": "매니저가 미승인한 휴무교환, 연차신청목록",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["replace_request"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "routeId": {
                    "example": "19"
                  },
                  "yearMonth": {
                    "example": "2022-01"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/managerWorkByDateAndRoute": {
      "post": {
        "description": "관리자 일자/노선별 근무/휴무자 조회",
        "tags": ["work"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "routeId": {
                    "example": "19"
                  },
                  "date": {
                    "example": "2021-11-01"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/stopworking": {
      "post": {
        "description": "벌칙,병가 사유로 승무정지된 정보등록",
        "tags": ["stopworking"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "startDate": {
                    "example": "2022-04-01"
                  },
                  "endDate": {
                    "example": "2022-04-01"
                  },
                  "driverId": {
                    "example": "371"
                  },
                  "workDay": {
                    "example": 12
                  },
                  "stopType": {
                    "example": "panelty"
                  }
                }
              }
            }
          }
        }
      },

      "get": {
        "description": "승무정지 리스트보기",
        "tags": ["stopworking"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/stopworking/{id}": {
      "get": {
        "description": "승무원별 stopworking정보조회",
        "tags": ["stopworking"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "put": {
        "description": "",
        "tags": ["stopworking"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "startDate": {
                    "example": "2022-04-01"
                  },
                  "endDate": {
                    "example": "2022-04-01"
                  },
                  "driverId": {
                    "example": "371"
                  },
                  "workDay": {
                    "example": 12
                  },
                  "stopType": {
                    "example": "panelty"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "description": "",
        "tags": ["stopworking"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {}
      }
    },
    "/api/bus/bulk": {
      "post": {
        "description": "bus 정보 일괄변경",
        "tags": ["bus"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "data": {
                    "example": [
                      {
                        "number": "경가999바9999",
                        "status": "NORMAL",
                        "busType": "GENERAL",
                        "companyId": 1,
                        "routeId": 100,
                        "managerId": 2221,
                        "isrun": 1
                      },
                      {
                        "number": "경가999바9991",
                        "status": "NORMAL",
                        "busType": "GENERAL",
                        "companyId": 1,
                        "routeId": 101,
                        "managerId": 2221
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/bus": {
      "post": {
        "description": "버스 정보등록",
        "tags": ["bus"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "number": {
                    "example": "경가999바9999"
                  },
                  "status": {
                    "example": "NORMAL"
                  },
                  "busType": {
                    "example": "GENERAL"
                  },
                  "companyId": {
                    "example": 1
                  },
                  "routeId": {
                    "example": 100
                  },
                  "managerId": {
                    "example": 2221
                  }
                }
              }
            }
          }
        }
      },

      "get": {
        "description": "BUS 리스트보기(?isrun=1&companyId=1&routeId=6)",
        "tags": ["bus"],
        "parameters": [
          {
            "name": "isrun",
            "description": "1:운행중, 0:폐차",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer"
            },
            "example": 1
          },
          {
            "name": "companyId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer"
            },
            "example": 1
          },
          {
            "name": "routeId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer"
            },
            "example": 6
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },

    "/api/bus/{id}": {
      "get": {
        "description": "BUS별 정보조회",
        "tags": ["bus"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": 6
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "put": {
        "description": "",
        "tags": ["bus"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "isrun": {
                    "example": 0
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "description": "",
        "tags": ["bus"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {}
      }
    },
    "/api/user/{id}": {
      "get": {
        "description": "승무원별정보 stopworking포함",
        "tags": ["user"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": 371
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/api/routedriver/bulk": {
      "put": {
        "description": "route,shift내의 fixed start order 일괄변경",
        "tags": ["routeDriver"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "data": {
                    "example": [
                      { "id": 3644, "fixedStartOrder": 1 },
                      { "id": 3647, "fixedStartOrder": 0 },
                      { "id": 4287, "fixedStartOrder": 2 }
                    ]
                  },
                  "duplicate": {
                    "example": ["fixedStartOrder"]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/buslocation/{routeId}": {
      "get": {
        "description": "실시간 BUS정류장 도착 정보조회",
        "tags": ["routeStation"],
        "parameters": [
          {
            "name": "routeId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/api/checkBusArrival": {
      "get": {
        "description": "최종정류장 도착 버스시간찾기",
        "tags": ["routeStation"],

        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/api/busedge/{routeId}": {
      "get": {
        "description": "Edge Device와 연동한 실시간 BUS정류장 도착 정보조회(개발중...)",
        "tags": ["routeStation"],
        "parameters": [
          {
            "name": "routeId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/api/work/bulk": {
      "put": {
        "description": "복수의 승무원work status를 한꺼번에 변경",
        "tags": ["work"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "data": {
                    "example": [
                      { "id": 61596, "status": "LEAVE_CHECK" },
                      { "id": 61597, "status": "WORK_CHECK" }
                    ]
                  },
                  "duplicate": {
                    "example": ["status"]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/work": {
      "get": {
        "description": "work with shift(?isrun=1&companyId=1&routeId=6)",
        "tags": ["work"],
        "parameters": [
          {
            "name": "routeId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer"
            },
            "example": 19
          },
          {
            "name": "date",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "2022-08-21"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/leavedatebydriver/{routeId}/{Shift}/{yearMonth}": {
      "get": {
        "description": "노선&조별 당월의 일별 휴무상태리스트",
        "tags": ["rest"],
        "parameters": [
          {
            "name": "routeId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": 21
          },
          {
            "name": "Shift",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "A"
          },
          {
            "name": "yearMonth",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2022-08"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/leaveSummaryByDriver/{routeId}/{date}": {
      "get": {
        "description": "각 매니저의 노선/영업소별 당월의 휴무자리스트 및 세부정보",
        "tags": ["work"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "routeId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": 19
          },
          {
            "name": "date",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2022-03-16"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/findshiftthismonth/{routeId}/{date}": {
      "get": {
        "description": "노선별 해당월의 시작조찾기",
        "tags": ["work"],
        "parameters": [
          {
            "name": "routeId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": 21
          },
          {
            "name": "date",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2022-06-23"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/routeListByManager/{placeId}/{datetime}": {
      "get": {
        "description": "매니저별 접근 시간에 따른 영업소 및 노선정보",
        "tags": ["route"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "placeId",
            "in": "path",
            "description": "placeId=-1 일 경우 매니저 관리 전 영업소",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": -1
          },
          {
            "name": "datetime",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2022-06-02 08:30:00"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/dispatchlist/{routeId}/{datetime}": {
      "get": {
        "description": "각 노선별 배차정보",
        "tags": ["dispatch"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "routeId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": 19
          },
          {
            "name": "datetime",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2021-11-20 08:30:00"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },

    "/api/rest/driver/{yearMonth}": {
      "get": {
        "description": "월별 승무원별 휴무신청리스트",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["rest"],
        "parameters": [
          {
            "name": "yearMonth",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2022-04"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/rest/manager/{yearMonth}/{routeId}": {
      "get": {
        "description": "관리자의 노선(들)의 월별 승무원별 휴무신청리스트",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["rest"],
        "parameters": [
          {
            "name": "yearMonth",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2022-04"
          },
          {
            "name": "routeId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": -1
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/rest": {
      "post": {
        "description": "휴무 신청정보 입력",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["rest"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "driverId": {
                    "example": "371"
                  },
                  "routeId": {
                    "example": "19"
                  },
                  "date": {
                    "example": "2022-04-01"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/rest/{id}": {
      "put": {
        "description": "",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["rest"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "date": {
                    "example": "2022-04-01"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "description": "",
        "tags": ["rest"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {}
      }
    },
    "/api/scheduleperiodfind/{routeId}/{yearMonth}": {
      "get": {
        "description": "노선별 당월의 휴무신청기간찾기",
        "tags": ["schedule_setting"],
        "parameters": [
          {
            "name": "routeId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": 19
          },
          {
            "name": "yearMonth",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2022-03"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/dailybusnumworknumyearmonth/{routeId}/{yearMonth}": {
      "get": {
        "description": "노선별 해당월의 가동대수/근무인원(routeId=-1이면 매니저관리 전노선)",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["route_setting", "work"],
        "parameters": [
          {
            "name": "routeId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": 19
          },
          {
            "name": "yearMonth",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2022-03"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/logresult": {
      "post": {
        "description": "sample swagger file출력",
        "tags": ["swagger"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "example": "apiname"
                  },
                  "security": {
                    "example": "false"
                  },
                  "multiexample": {
                    "example": "false"
                  },
                  "attributes": {
                    "example": ["pros1", "props2"]
                  },
                  "include": {
                    "example": ["get", "getAll", "post", "put", "delete"]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/cronschedule": {
      "post": {
        "description": "버스,승무원의 변경예정내역을 등록함.",
        "tags": ["cronSchedule"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "busId": {
                    "type": "integer"
                  },
                  "driverId": {
                    "type": "integer"
                  },
                  "changeDate": {
                    "type": "string"
                  },
                  "routeId": {
                    "type": "integer"
                  },
                  "shift": {
                    "type": "string"
                  },
                  "driverBusId": {
                    "type": "integer"
                  }
                }
              },
              "examples": {
                "Bus": {
                  "value": {
                    "BusId": 10,
                    "changeDate": "2022-08-13",
                    "routeId": 19
                  }
                },
                "Dirver": {
                  "value": {
                    "driverId": 11,
                    "changeDate": "2022-08-13",
                    "routeId": 19,
                    "shift": "A",
                    "driverBusId": 11
                  }
                }
              }
            }
          }
        }
      },

      "get": {
        "description": "버스/승무원 변경예약 리스트보기",
        "tags": ["cronSchedule"],
        "parameters": [
          {
            "name": "busId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "$not null"
          },
          {
            "name": "driverId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "$not null"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/cronschedule/{id}": {
      "get": {
        "description": "버스/승무원별 변경예약 내역조회",
        "tags": ["cronSchedule"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "put": {
        "description": "버스/승무원별 변경예약 내용 변경",
        "tags": ["cronSchedule"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "busId": {
                    "type": "integer"
                  },
                  "driverId": {
                    "type": "integer"
                  },
                  "changeDate": {
                    "type": "string"
                  },
                  "routeId": {
                    "type": "integer"
                  },
                  "shift": {
                    "type": "string"
                  },
                  "driverBusId": {
                    "type": "integer"
                  }
                }
              },
              "examples": {
                "Bus": {
                  "value": {
                    "BusId": 10,
                    "changeDate": "2022-08-13",
                    "routeId": 19
                  }
                },
                "Dirver": {
                  "value": {
                    "driverId": 11,
                    "changeDate": "2022-08-13",
                    "routeId": 19,
                    "shift": "A",
                    "driverBusId": 11
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "description": "",
        "tags": ["cronSchedule"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {}
      }
    },
    "/api/cronStart": {
      "get": {
        "description": "cronJob을 일괄 실행함",
        "tags": ["cronTimer"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/cronStop": {
      "get": {
        "description": "cronJob을 일괄 중지함",
        "tags": ["cronTimer"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/cronTimer": {
      "post": {
        "description": "",
        "tags": ["cronTimer"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "pattern": {
                    "type": "string"
                  },
                  "message": {
                    "type": "string"
                  },
                  "action": {
                    "type": "string"
                  },
                  "isActive": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "1분간격으로": {
                  "value": {
                    "title": "차고지 버스도착시간 체크",
                    "pattern": "* * * * *",
                    "message": "",
                    "action": "() => {reqres.axiosRun('post', 'http://kikibus.iptime.org:8484/api/busLocation');}",
                    "isactive": 1
                  }
                },
                "매일2:00am": {
                  "value": {
                    "title": "",
                    "pattern": "0 2 * * * *",
                    "message": "",
                    "action": "() => {const replacement = {param1:'a',param2:'b'}; reqres.noResponseBody(storedprocedurename(:param1,:param2), replacement, 'INSERT', next);}",
                    "isactive": 0
                  }
                },
                "매월1일 2:00am": {
                  "value": {
                    "title": "",
                    "pattern": "0 2 1 * *",
                    "message": "",
                    "action": "",
                    "isactive": 0
                  }
                },
                "매월3째주 화요일 2:00am": {
                  "value": {
                    "title": "",
                    "pattern": "00 02 15-21 * 2",
                    "message": "",
                    "action": "",
                    "isactive": 0
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "description": "",
        "tags": ["cronTimer"],
        "parameters": [
          {
            "name": "title",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": ""
          },
          {
            "name": "pattern",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": ""
          },
          {
            "name": "message",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": ""
          },
          {
            "name": "action",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": ""
          },
          {
            "name": "isActive",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": ""
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/cronTimer/{id}": {
      "get": {
        "description": "",
        "tags": ["cronTimer"],
        "parameters": [
          {
            "name": "title",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": ""
          },
          {
            "name": "pattern",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": ""
          },
          {
            "name": "message",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": ""
          },
          {
            "name": "action",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": ""
          },
          {
            "name": "isActive",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": ""
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "put": {
        "description": "",
        "tags": ["cronTimer"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "pattern": {
                    "type": "string"
                  },
                  "message": {
                    "type": "string"
                  },
                  "action": {
                    "type": "string"
                  },
                  "isActive": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "일정교체": {
                  "value": {
                    "pattern": "0 2 * * *",
                    "isActive": 1
                  }
                },
                "서비스중지": {
                  "value": {
                    "isActive": 0
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "description": "",
        "tags": ["cronTimer"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {}
      }
    },
    "/api/motionCapture": {
      "post": {
        "description": "",
        "tags": ["motionCapture"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "detectionTime": {
                    "example": ""
                  },
                  "busName": {
                    "example": ""
                  },
                  "isbelt": {
                    "example": ""
                  },
                  "iscellphone": {
                    "example": ""
                  },
                  "imageId": {
                    "example": ""
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "description": "",
        "tags": ["motionCapture"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/motionCapture/{id}": {
      "get": {
        "description": "",
        "tags": ["motionCapture"],

        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/api/edgeDevice": {
      "post": {
        "description": "",
        "tags": ["edgeDevice"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "lon": {
                    "example": ""
                  },
                  "lat": {
                    "example": ""
                  },
                  "time": {
                    "example": ""
                  },
                  "busName": {
                    "example": ""
                  },
                  "speed": {
                    "example": ""
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "description": "",
        "tags": ["edgeDevice"],

        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/api/edgeDevice/{id}": {
      "get": {
        "description": "",
        "tags": ["edgeDevice"],

        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "in": "header",
        "bearerFormat": "JWT"
      }
    }
  }
}
